import type { Metadata } from 'next'
import { Ubuntu } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/Sidebar'

const ubuntu = Ubuntu({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Multi-step Form',
  description: 'Generated by create next app',
  icons: {
    icon: './images/favicon-32x32.png',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.className} bg-alabaster lg:bg-white antialiased grid grid-cols-1 lg:grid-cols-[274px_1fr] lg:p-4 lg:w-screen lg:h-screen`}
      >
        <Sidebar />
        <main className="px-4 lg:px-0 flex justify-center lg:justify-start">{children}</main>
      </body>
    </html>
  )
}
